/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biro_view;

import biro_koneksi.koneksi;
import java.awt.Color;
import java.awt.Component;
import java.awt.ComponentOrientation;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Insets;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.Shape;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.geom.Line2D;
import java.awt.geom.RoundRectangle2D;
import static java.lang.Integer.parseInt;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.border.AbstractBorder;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author febri
 */
public class lis_tiket extends javax.swing.JFrame {
    Connection conn;
    PreparedStatement ps;
    ResultSet rs;
    public static String idWisata;    
    public static String namaWisata;    
    public static String foto_file;   
    public static String id_tiket;


    public lis_tiket() {                
        setUndecorated(true);
        initComponents();
        this.setBackground(new Color(0.0f,0.0f,0.0f,0.0f));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel =  new RoundedPanel(32,new java.awt.Color(242,242,242));
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        f_nama = new javax.swing.JTextField();
        f_nama1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t_wisata = new javax.swing.JTextField();
        j_tiket = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        total_pem = new javax.swing.JTextField();
        alfamart = new javax.swing.JLabel();
        indo = new javax.swing.JLabel();
        randomcode1 = new javax.swing.JTextField();
        back = new javax.swing.JLabel();
        bayar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(255, 255, 255, 0));
        panel.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                panelComponentAdded(evt);
            }
        });
        panel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                panelComponentShown(evt);
            }
        });

        jLabel5.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\febri\\OneDrive\\Desktop\\x aja.png")); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel8.setText("BIRO WISATA");

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabel);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("UPDATE TIKET");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Nama");

        f_nama = new RoundJTextField(10);
        //f_nama.setBorder(BorderFactory.createEmptyBorder(4,4,4,4));
        f_nama.setBorder(new LineBorder(Color.BLACK, 2));
        f_nama.setHorizontalAlignment(JTextField.CENTER);

        f_nama1 = new RoundJTextField(10);
        //f_nama.setBorder(BorderFactory.createEmptyBorder(4,4,4,4));
        f_nama1.setBorder(new LineBorder(Color.BLACK, 2));
        f_nama1.setHorizontalAlignment(JTextField.CENTER);
        f_nama1.setText("1");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("No Tiket");

        t_wisata = new RoundJTextField(10);
        //f_nama.setBorder(BorderFactory.createEmptyBorder(4,4,4,4));
        t_wisata.setBorder(new LineBorder(Color.BLACK, 2));
        t_wisata.setHorizontalAlignment(JTextField.CENTER);

        j_tiket = new RoundJTextField(10);
        //f_nama.setBorder(BorderFactory.createEmptyBorder(4,4,4,4));
        j_tiket.setBorder(new LineBorder(Color.BLACK, 2));
        j_tiket.setHorizontalAlignment(JTextField.CENTER);
        j_tiket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                j_tiketKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                j_tiketKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Jumlah Tiket");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Tempat Wisata");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Total Bayar");

        total_pem = new RoundJTextField(10);
        //f_nama.setBorder(BorderFactory.createEmptyBorder(4,4,4,4));
        total_pem.setBorder(new LineBorder(Color.BLACK, 2));
        total_pem.setHorizontalAlignment(JTextField.CENTER);

        alfamart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biro_image/Alfamart.png"))); // NOI18N
        alfamart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alfamartMouseClicked(evt);
            }
        });

        indo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biro_image/indomaret.png"))); // NOI18N
        indo.setToolTipText("");
        indo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                indoMouseClicked(evt);
            }
        });

        randomcode1 = new RoundJTextField(10);
        //f_nama.setBorder(BorderFactory.createEmptyBorder(4,4,4,4));
        randomcode1.setBorder(new LineBorder(Color.BLACK, 2));
        randomcode1.setHorizontalAlignment(JTextField.CENTER);
        randomcode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomcode1ActionPerformed(evt);
            }
        });

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biro_image/cancel.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        bayar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biro_image/read.png"))); // NOI18N
        bayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bayarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel6))
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(panelLayout.createSequentialGroup()
                                                .addGap(84, 84, 84)
                                                .addComponent(f_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(f_nama1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel4)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(24, 24, 24)
                                        .addComponent(t_wisata, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14))
                                        .addGap(43, 43, 43)
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(j_tiket, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(total_pem, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(309, 309, 309))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addComponent(alfamart)
                                        .addGap(18, 18, 18)
                                        .addComponent(indo))
                                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(panelLayout.createSequentialGroup()
                                            .addComponent(back)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(bayar))
                                        .addComponent(randomcode1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(427, 427, 427))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(f_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(8, 8, 8))
                    .addComponent(f_nama1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_wisata, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(j_tiket, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(total_pem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alfamart)
                    .addComponent(indo))
                .addGap(18, 18, 18)
                .addComponent(randomcode1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(bayar))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panelComponentShown
        conn = koneksi.konek();
    }//GEN-LAST:event_panelComponentShown

    private void panelComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_panelComponentAdded
       
        t_wisata.setEditable(false);
        total_pem.setEditable(false);
        f_nama1.setEditable(false);
        
        alfamart.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        indo.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        bayar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        back.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        conn            = koneksi.konek();
        String sql      = " SELECT id_tiket, nama_pelanggan, jumlah_tiket, wisata_name, harga, tanggal_beli, kode_bayar FROM tiket aa JOIN wisata bb ON aa.id_wisata = bb.id ";

        try {
            ps          = conn.prepareStatement(sql);
            rs          = ps.executeQuery();
            
            DefaultTableModel model         = new DefaultTableModel(new String[]{"Nama", "Jumlah Tiket", "Nama Wisata", "Harga","Kode Bayar"}, 0);
            
            while (rs.next()) {
                id_tiket = rs.getString("id_tiket");
                
                String nama_pelanggan       = rs.getString("nama_pelanggan");
                String jumlah_tiket         = rs.getString("jumlah_tiket");
                String wisata_name          = rs.getString("wisata_name");
                String harga                = rs.getString("harga");
//                String tanggal_beli         = rs.getString("tanggal_beli");
                String kode_bayar           = rs.getString("kode_bayar");
                
                model.addRow(new Object[]{nama_pelanggan, jumlah_tiket, wisata_name, harga, kode_bayar});
            }
            
            tabel.setModel(model);
            tabel.setBackground(Color.LIGHT_GRAY);
            tabel.setForeground(Color.black);
            
            Font font = new Font("",1,22);
            tabel.setFont(font);
            tabel.setRowHeight(30);
            
            tabel.addMouseListener(new MouseAdapter(){
                @Override
                public void mouseClicked(MouseEvent e){

                    // i = the index of the selected row
                    int i = tabel.getSelectedRow();

                    f_nama.setText(model.getValueAt(i, 0).toString());        
                    j_tiket.setText(model.getValueAt(i, 1).toString());
                    t_wisata.setText(model.getValueAt(i, 2).toString());                    
                    total_pem.setText(model.getValueAt(i, 3).toString());
                    
//                    textId.setText(model.getValueAt(i, 0).toString());
//                    textFname.setText(model.getValueAt(i, 1).toString());
//                    textLname.setText(model.getValueAt(i, 2).toString());
//                    textAge.setText(model.getValueAt(i, 3).toString());
                }
            });
          
          } catch(SQLException e) {
            e.printStackTrace();
          }
    }//GEN-LAST:event_panelComponentAdded

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void alfamartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alfamartMouseClicked
        conn            = koneksi.konek();

        Random random   = new Random();
        long first14    = (long) (Math.random() * 100000000000000L);
        long number     = 8800000000000000L + first14;
        String sql      = "SELECT * FROM tiket where kode_bayar = "+number+"";
        //        String sql      = "SELECT * FROM tiket where kode_bayar = '8897305748730586'";
        //        JOptionPane.showMessageDialog(rootPane, sql);

        try {
            ps    = conn.prepareStatement(sql);
            rs    = ps.executeQuery();
            //            JOptionPane.showMessageDialog(rootPane, rs.getString("kode_bayar"));

            if (rs.next() == false) {
                randomcode1.setText(String.valueOf(number));
            }else{
                long first15    = (long) (Math.random() * 100000000000000L);
                long number2    = 8800000000000000L + first15;

                randomcode1.setText(String.valueOf(number2));
            }

            randomcode1.setVisible(true);
            randomcode1.setEditable(false);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_alfamartMouseClicked

    private void indoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_indoMouseClicked
        conn            = koneksi.konek();

        Random random   = new Random();
        long first14    = (long) (Math.random() * 100000000000000L);
        long number     = 7700000000000000L + first14;
        String sql      = "SELECT * FROM tiket where kode_bayar = "+number+"";
        //        String sql      = "SELECT * FROM tiket where kode_bayar = '8897305748730586'";
        //        JOptionPane.showMessageDialog(rootPane, sql);

        try {
            ps    = conn.prepareStatement(sql);
            rs    = ps.executeQuery();
            //            JOptionPane.showMessageDialog(rootPane, rs.getString("kode_bayar"));

            if (rs.next() == false) {
                randomcode1.setText(String.valueOf(number));
            }else{
                long first15    = (long) (Math.random() * 100000000000000L);
                long number2    = 7700000000000000L + first15;

                randomcode1.setText(String.valueOf(number2));
            }

            randomcode1.setVisible(true);
            randomcode1.setEditable(false);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_indoMouseClicked

    private void randomcode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomcode1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_randomcode1ActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        pemesanan_tiket back;
        back = new pemesanan_tiket();
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void bayarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bayarMouseClicked
//        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
//        LocalDateTime now = LocalDateTime.now();

        String namaPembeli  = f_nama.getText();        
        String j_tiket      = this.j_tiket.getText();
        String kode_bayar   = randomcode1.getText();        
        String total_pem    = this.total_pem.getText();
        String total_pemba  = total_pem.replace(".","");
        
        System.err.println(total_pem);
        System.err.println(total_pemba);
        String sql = "UPDATE tiket SET nama_pelanggan = '"+namaPembeli+"', jumlah_tiket = '"+j_tiket+"', kode_bayar = '"+kode_bayar+"', harga = '"+total_pemba+"' WHERE id_tiket = '"+id_tiket+"' ";

        System.out.println(sql);
        try {
            ps = conn.prepareStatement(sql);

            ps.execute();
            String result = "Update Success Menunggu konfirmasi pembayaran ";
            JOptionPane.showMessageDialog(rootPane, result);

            menu pindah = new menu();
            pindah.setVisible(true);
            dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_bayarMouseClicked

    private void j_tiketKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_j_tiketKeyPressed

    }//GEN-LAST:event_j_tiketKeyPressed

    private void j_tiketKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_j_tiketKeyReleased
        String j_tiket      = this.j_tiket.getText();
        int harga_total     = parseInt(j_tiket)*50000;
        
        DecimalFormat formatter = (DecimalFormat) NumberFormat.getInstance(Locale.US);
        DecimalFormatSymbols symbols = formatter.getDecimalFormatSymbols();

        BigDecimal bd = new BigDecimal(harga_total);

        symbols.setGroupingSeparator('.');
        formatter.setDecimalFormatSymbols(symbols);
        total_pem.setText(formatter.format(bd.longValue()));
    }//GEN-LAST:event_j_tiketKeyReleased

    class RoundedPanel extends JPanel{
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border            
        }
    }

    public class RoundedBorder extends AbstractBorder {

        public RoundedBorder(Color c, int g) {
            color = c;
            gap = g;
        }

        @Override
        public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
            super.paintBorder(c, g, x, y, width, height);
            Graphics2D g2d;
            if (g instanceof Graphics2D) {
                g2d = (Graphics2D) g;
                g2d.setColor(color);
                System.out.println(x + y);
                g2d.draw(new Line2D.Double((double)x, (double)y + 10, (double)x + 3, (double)y + 3));
                g2d.draw(new Line2D.Double((double)x + 3, (double)y + 3, (double)x + 10, (double)y));
                g2d.draw(new Line2D.Double((double)x + 10, (double)y, (double)x + 30, (double)y));
                g2d.draw(new Line2D.Double((double)x + 30, (double)y, (double)x + 33, (double)y + 2));
                g2d.draw(new Line2D.Double((double)x + 33, (double)y + 2, (double)x + 36, (double)y + 8));
                g2d.draw(new Line2D.Double((double)x + 36, (double)y + 8, (double)x + 36, (double)y + 28));
                g2d.draw(new Line2D.Double((double)x + 36, (double)y + 28, (double)x + 34, (double)y + 31));
                g2d.draw(new Line2D.Double((double)x + 34, (double)y + 31, (double)x + 32, (double)y + 33));
                g2d.draw(new Line2D.Double((double)x + 32, (double)y + 33, (double)x + 6, (double)y + 33));
                g2d.draw(new Line2D.Double((double)x + 6, (double)y + 33, (double)x + 3, (double)y + 31));
                g2d.draw(new Line2D.Double((double)x + 3, (double)y + 31, (double)x, (double)y + 27));
                g2d.draw(new Line2D.Double((double)x, (double)y + 27, (double)x, (double)y + 10));
            }
        }

        @Override
        public Insets getBorderInsets(Component c) {
            return (getBorderInsets(c, new Insets(gap, gap, gap, gap)));
        }

        @Override
        public Insets getBorderInsets(Component c, Insets insets) {
            insets.left = insets.top = insets.right = insets.bottom = gap;
            return insets;
        }

        @Override
        public boolean isBorderOpaque() {
            return true;
        }

        // Variable declarations
        private final Color color;
        private final int gap;
    }
    
    public class RoundJTextField extends JTextField {
        private Shape shape;
        public RoundJTextField(int size) {
            super(size);
            setOpaque(false); // As suggested by @AVD in comment.
        }
        protected void paintComponent(Graphics g) {
             g.setColor(getBackground());
             g.fillRoundRect(0, 0, getWidth()-1, getHeight()-1, 15, 15);
             super.paintComponent(g);
        }
        protected void paintBorder(Graphics g) {
             g.setColor(getForeground());
             g.drawRoundRect(0, 0, getWidth()-1, getHeight()-1, 15, 15);
        }
        public boolean contains(int x, int y) {
             if (shape == null || !shape.getBounds().equals(getBounds())) {
                 shape = new RoundRectangle2D.Float(0, 0, getWidth()-1, getHeight()-1, 15, 15);
             }
             return shape.contains(x, y);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lis_tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lis_tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lis_tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lis_tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lis_tiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alfamart;
    private javax.swing.JLabel back;
    private javax.swing.JLabel bayar;
    private javax.swing.JTextField f_nama;
    private javax.swing.JTextField f_nama1;
    private javax.swing.JLabel indo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField j_tiket;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField randomcode1;
    private javax.swing.JTextField t_wisata;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField total_pem;
    // End of variables declaration//GEN-END:variables
}
